name: prebid-integration-test
on: [push]
jobs:
  test-emx-adapter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: >
          git submodule init
          git submodule update
          cd Prebid.js
          npm install
          gulp build --modules=emx_digitalBidAdapter,appnexusBidAdapter
          gulp test --file "test/spec/modules/emx_digitalBidAdapter_spec.js" 
          cd ..
          npm install 
          node integration_test.js
